import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import {
  Document, Paragraph, TextRun, HeadingLevel, Packer,
  AlignmentType, PageNumber, Footer, Table, TableRow, TableCell,
  WidthType, BorderStyle
} from 'docx';

interface DocSection {
  heading: string;
  content: string;
  level?: number;  // 1-4, default 1
  table?: { headers: string[]; rows: string[][] };
}

export async function generateWord(
  data: { title: string; sections: DocSection[]; filename?: string },
  outputDir?: string
): Promise<string> {
  const children: any[] = [];

  // Title
  children.push(new Paragraph({
    text: data.title,
    heading: HeadingLevel.TITLE,
    spacing: { after: 400 }
  }));

  // Date
  children.push(new Paragraph({
    children: [
      new TextRun({ text: `Generated by AirBrowse on ${new Date().toLocaleDateString()}`, italics: true, color: '888888' })
    ],
    spacing: { after: 400 }
  }));

  // Sections
  for (const section of data.sections) {
    const headingLevel = [HeadingLevel.HEADING_1, HeadingLevel.HEADING_2, HeadingLevel.HEADING_3, HeadingLevel.HEADING_4][(section.level ?? 1) - 1] ?? HeadingLevel.HEADING_1;

    children.push(new Paragraph({
      text: section.heading,
      heading: headingLevel,
      spacing: { before: 400, after: 200 }
    }));

    // Content paragraphs
    const paragraphs = section.content.split('\n\n');
    for (const para of paragraphs) {
      if (para.trim()) {
        children.push(new Paragraph({
          children: [new TextRun({ text: para.trim(), font: 'Arial', size: 24 })],
          spacing: { after: 200 }
        }));
      }
    }

    // Table if present
    if (section.table) {
      const tableRows: TableRow[] = [];

      // Header row
      tableRows.push(new TableRow({
        children: section.table.headers.map(h => new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, font: 'Arial', size: 20 })] })],
          width: { size: Math.floor(100 / section.table!.headers.length), type: WidthType.PERCENTAGE }
        }))
      }));

      // Data rows
      for (const row of section.table.rows) {
        tableRows.push(new TableRow({
          children: row.map(cell => new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: String(cell), font: 'Arial', size: 20 })] })],
          }))
        }));
      }

      children.push(new Table({ rows: tableRows }));
    }
  }

  const doc = new Document({
    sections: [{ children }],
    styles: {
      default: {
        document: { run: { font: 'Arial', size: 24 } }
      }
    }
  });

  const dir = outputDir ?? getOutputDir();
  const filename = data.filename ?? `airbrowse-export-${Date.now()}.docx`;
  const filePath = path.join(dir, filename);

  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync(filePath, buffer);

  const uri = vscode.Uri.file(filePath);
  await vscode.commands.executeCommand('vscode.open', uri);

  return filePath;
}

function getOutputDir(): string {
  const workspaceFolders = vscode.workspace.workspaceFolders;
  if (workspaceFolders && workspaceFolders.length > 0) {
    return workspaceFolders[0].uri.fsPath;
  }
  return require('os').homedir();
}
